version: "3.9"

services:
    db:
        image: postgres:15.2-alpine3.17
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: users_db
        ports:
            - 5432:5432
        command: postgres -c max_connections=300

    flyway:
        image: flyway/flyway:9.15.0-alpine
        command: -url=jdbc:postgresql://db:5432/users_db -user=root -password=password -connectRetries=60 migrate
        volumes:
            - ./server/database/sql:/flyway/sql
        depends_on:
            - db

    users-ms:
        build: .
        ports:
            - 8000:8000
        volumes:
            - .:/app
        command: npm run devstart
        depends_on:
            - db
            - flyway
    
    tests:
        build: .
        command: npm run test
        depends_on:
            - db
            - flyway
            - users-ms
