swagger: "2.0"
info:
    title: "Users-ms"
    description: "API documentation for the Users microservice"
    version: 1.0.0
paths:
    /users/create:
        post: 
            requestBody: 
                required: true
                content: 
                    application/json:
                        schema: 
                            type: object
                            properties: 
                                firstName: 
                                    type: string
                                    description: The first name of the user
                                lastName: 
                                    type: string
                                    description: The last name of the user
                                email: 
                                    type: string
                                    description: The email address of the user
                        required:
                            - firstName
                            - lastName
                            - email
            responses:
                '201': 
                    description: User created successfully
                    content:
                        application/json:
                        schema:
                            type: object
                            properties:
                            id:
                                type: string
                                format: uuid
                                description: The unique identifier of the user
                '500':
                    description: Internal server error

securityDefinitions:
    JWT:
        type: apiKey
        in: header
        name: Authorization
